version: '3.9'

services:   
  # node-app:
  #   build:
  #     context: .
  #   command: npm run watch
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "6001:6000"
  #   depends_on:
  #     - mongo
  #   links: 
  #     - "mongo:mongodb_url"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'